# 邮箱配置
EMAIL_ADDRESS: ${EMAIL_ADDRESS}
EMAIL_USE_TLS: ${EMAIL_USE_TLS}
EMAIL_USE_SSL: ${EMAIL_USE_SSL}
EMAIL_HOST: ${EMAIL_HOST}
EMAIL_PORT: ${EMAIL_PORT}
EMAIL_HOST_USER: ${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

# 数据库链接信息
DB_NAME: maxkb
DB_HOST: ora3.880219.xyz
DB_PORT: 55612
DB_USER: maxkb
DB_PASSWORD: cGEXwWin5tje
DB_ENGINE: django.db.backends.postgresql_psycopg2
EMBEDDING_MODEL_PATH: /teamspace/studios/model-dataset/model
EMBEDDING_MODEL_NAME: /teamspace/studios/model-dataset/model/shibing624-text2vec-base-chinese
TOKENIZER_PATH: /teamspace/studios/model-dataset/model/tokenizer
TOKENIZER_NAME: /teamspace/studios/model-dataset/model/tokenizer/openai-community-gpt2




DEBUG: false